### ISSUE TITLE
Capability to load external resources in CLI config YAML files

### ISSUE THREAD

**Issue by mbabadi** [cellarium-ai/cellarium-ml#111]
We need to have `cellarium.ml.transform.Filter` to load `filter_list` from e.g. a text or csv file. This information is not in a checkpoint, so CheckpointField does not quite work. Perhaps we could unify CheckpointField and whatever this feature will generate into a same mechanism: loading a resource file (could be a pickled dictionary), caching it, and returning a specific key.

**Comment by ordabayevy** [comment]
There turns out to be a very simple way to add things similar to `CheckpointField` using yaml tags and constructors (https://matthewpburruss.com/post/yaml/)

A general object loader could look like this:

```py
@dataclass
class ObjectLoader:
    file_path: str
    loader_fn: Callable
    attr: Optional[str] = None
    convert_fn: Optional[Callable] = None

    def __new__(cls, file_path, loader_fn, attr, convert_fn):
        obj = loader_fn(file_path)
        if attr is not None:
            obj = getattr(obj, attr)
        if convert_fn is not None:
            obj = convert_fn(obj)
        return obj
```

Corresponding yaml file would look like this:

```yaml
model:
  transforms:
    - class_path: cellarium.ml.transforms.ZScore
      init_args:
        meang_g:
          !ObjectLoader
          file_path: onepass_ckpt_path
          loader_fn: cellarium.ml.core.CellariumModule.load_from_checkpoint
          attr: mean_g
          convert_fn: null
```
