### ISSUE TITLE
scvi: include the option to limit to a specific set of genes

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#204]
We want a way to on-the-fly subset to a specific list of genes.

We do not want the dataloader to load the entire set of genes because this would be a big waste of memory / cuda memory.

Should this be a transform?  It seems like a transform happens too late... I think we'd really like this to be part of the dataloader itself.  Any thoughts @ordabayevy ?

What if we just wrote a new `convert_fn` for `X` to be used here in the config file?
```yaml
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      ...
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.subset_genes_and_densify
```
